"""Exercise 1.3 -- the same loop, driving a real finite element code.

Nothing structural changes from ex2. The tool schema list is imported instead of
written inline, and the dispatch is one generic call instead of a hard-coded
function. That is the whole diff -- and it is the point: the loop does not care
what the tools do. Swap in a mesher and a solver and you have an agent that runs
simulations.

The task below is deliberately multi-step. The agent has to mesh first, notice
the mesh file name that came back, and feed it to the solver. Watch the printed
trace: you are watching it plan, not just answer.

Run:  python ex3_agent_loop.py

Units: SI throughout (m, N, Pa).
"""

import json
import os

from openai import OpenAI

# The tool layer: TOOLS is the list of schemas the model reads, execute_tool is
# the dispatcher that actually calls into the mesher and solver. Keeping these
# two together in one module means the loop below never mentions a tool by name.
from tet10.tools import TOOLS, execute_tool

client = OpenAI(base_url=os.environ["LLM_BASE_URL"], api_key=os.environ["LLM_API_KEY"])
MODEL = os.environ.get("LLM_MODEL", "gemini-2.5-flash")

MAX_TURNS = 15

TASK = (
    "Mesh a 0.2 x 0.02 x 0.02 m cantilever, fix xmin, apply 1 kN downward at "
    "xmax, and report the maximum deflection and von Mises stress. Use steel: "
    "E = 200 GPa, nu = 0.3."
)

messages = [
    {
        "role": "system",
        "content": (
            "You are a finite element analyst. Use the provided tools to build and "
            "run the model; do not estimate results you could compute. All values "
            "are SI (meters, newtons, pascals). Loads are applied as tractions in "
            "Pa, so convert a point load to a traction over the loaded surface "
            "area. When you have results, report them with units and say whether "
            "they look physically reasonable."
        ),
    },
    {"role": "user", "content": TASK},
]

print(f"TASK: {TASK}\n")

for turn in range(MAX_TURNS):
    print(f"--- turn {turn + 1} ---")

    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        tools=TOOLS,
    )
    assistant_message = response.choices[0].message

    # No tool calls -> the model is done and `content` is the final answer.
    if not assistant_message.tool_calls:
        print("\n=== FINAL ANSWER ===")
        print(assistant_message.content)
        break

    # Some models narrate their plan in `content` while also requesting tools.
    # Worth printing -- it is the closest thing to seeing it think.
    if assistant_message.content:
        print(f"[model] {assistant_message.content.strip()}")

    # Record the request before running anything: the API requires each tool
    # result to follow the assistant message that asked for it.
    messages.append(
        {
            "role": "assistant",
            "content": assistant_message.content or "",
            "tool_calls": [
                {
                    "id": tool_call.id,
                    "type": "function",
                    "function": {
                        "name": tool_call.function.name,
                        "arguments": tool_call.function.arguments,
                    },
                }
                for tool_call in assistant_message.tool_calls
            ],
        }
    )

    # Generic dispatch: one line, any number of tools. Contrast with ex2's
    # single hard-coded function.
    for tool_call in assistant_message.tool_calls:
        name = tool_call.function.name

        # `arguments` is a JSON string generated by the model, so it can be
        # malformed. Handle that as a tool result, not a crash -- the model can
        # read the complaint and try again.
        try:
            arguments = json.loads(tool_call.function.arguments)
        except json.JSONDecodeError as exc:
            arguments = None
            result = json.dumps({"error": f"arguments were not valid JSON: {exc}"})
        else:
            # execute_tool never raises: failures come back as {"error": ...} so
            # the agent can recover from them itself.
            result = execute_tool(name, arguments)

        print(f"  -> call: {name}")
        print(f"     args: {json.dumps(arguments) if arguments is not None else tool_call.function.arguments}")
        print(f"     result: {result}")

        # One tool message per call, each tagged with the id it answers.
        messages.append(
            {
                "role": "tool",
                "tool_call_id": tool_call.id,
                "content": result,
            }
        )

    print()

else:
    print(
        f"\nHit the {MAX_TURNS}-turn limit without a final answer. "
        "The agent is probably stuck in a retry cycle -- scroll up and read the "
        "last few tool results to see what it kept failing on."
    )
